export const ACTIONTYPES = {
    NOTIFICATION_START_WAITING: "NOTIFICATION_START_WAITING",
    NOTIFICATION_STOP_WAITING: "NOTIFICATION_STOP_WAITING",
    GET_ALL_ALBUMS: "GET_ALL_ALBUMS",
    GET_ALL_SONGS : "GET_ALL_SONGS",
    CHANGE_VIEW: "CHANGE_VIEW",
    CHANGE_SONG: "CHANGE_SONG",
    ADD_TO_HISTORY: "ADD_TO_HISTORY",
    REMOVE_FROM_HISTORY: "REMOVE_FROM_HISTORY"
};